version: 1.0

deploy:
  # configuration part, which is taken at the FIRST deployment of each branch
  bootstrap:
    # folders that are not copied to IONOS webspace
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
    # commands that are executed at the real webspace NOT at build servers AFTER copying new files
    post-deployment-remote-commands:
      - mkdir -p var/log var/cache
      - chmod -R 775 var
      - APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear
      - APP_ENV=prod APP_DEBUG=0 php bin/console cache:warmup

  # configuration part, which is taken at ALL FURTHER deployments of this branch
  recurring:
    # folders that are not copied to IONOS webspace
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
      - var
    # commands that are executed at the real webspace NOT at build servers BEFORE copying new files
    pre-deployment-remote-commands:
      - echo "here you could enter maintenance mode..."
    # commands that are executed at the real webspace NOT at build servers AFTER copying new files
    post-deployment-remote-commands:
      - chmod -R 775 var
      - APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear
      - APP_ENV=prod APP_DEBUG=0 php bin/console cache:warmup

# uncomment the following lines to configure cron jobs
#runtime:
#  cron-jobs:
#    - command: my-cron-job-command # the deployment is located at $HOME/htdocs/ to execute a deployed script just prefix it accordingly
#      schedule: 0 5 * * * # run every day at 5:00
